services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyspark-data-engineering:latest
    container_name: hexdata
    hostname: hexdata

    environment:
      - JUPYTER_TOKEN=
      - JUPYTER_PORT=8888

    ports:
      - "${JUPYTER_PORT:-8888}:8888"

    volumes:
      - ${WORK_DIR:-./work}:/home/hexdata/work
      - .:/home/hexdata/code

    # Inicia o Jupyter Lab diretamente, sem passar pelo start.sh
    command: /bin/bash -c "/opt/conda/bin/jupyter lab --ip=0.0.0.0 --no-browser --IdentityProvider.token='' 2>&1"
